services:
    lsiim_annotation:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - VITE_API=http://172.29.207.16:5001
                - VITE_VIDEOS_BASE_PATH=http=D:/drives/lsiim/laprem_dataset/recordings
        ports:
            - "5173:80"
        environment:
            - NODE_ENV=production
            - VITE_API=http://172.29.207.16:5001
            - VITE_VIDEOS_BASE_PATH=http=D:/drives/lsiim/laprem_dataset/recordings
        volumes:
            - .:/app
        networks:
            - lsiimnet

networks:
    lsiimnet:
        driver: bridge
    # external: true # Usar a rede externa definida no primeiro projeto
