version: '1.0.0'
services:
  lsiim_annotation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    networks:
      - lsiimnet

networks:
  lsiimnet:
    driver: bridge