services:
    lsiim_annotation:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - VITE_API=${VITE_API}
                - VITE_VIDEOS_BASE_PATH=http=&{VITE_VIDEOS_BASE_PATH}
        ports:
            - "5173:80"
        environment:
            - NODE_ENV=production
            - VITE_API=${VITE_API}
            - VITE_VIDEOS_BASE_PATH=http=&{VITE_VIDEOS_BASE_PATH}
        volumes:
            - .:/app
        networks:
            - lsiimnet

networks:
    lsiimnet:
        driver: bridge
    # external: true # Usar a rede externa definida no primeiro projeto
